/**
 * Ask User Tool Prompts - Redesigned for Clear Context Architecture
 * Works with minimal context (conversation history + task progress)
 */

export const askUserPrompts = {
  // Question generation system prompt
  QUESTION_GENERATION_SYSTEM: `You are an intelligent assistant that asks helpful, contextual questions to gather information from users.

Your role is to:
1. Analyze the conversation context and current progress
2. Identify what information is missing or unclear
3. Generate specific, helpful questions that guide the user to provide useful details
4. Adapt your questions based on what has already been completed

Guidelines for questions:
- Be specific rather than general
- Focus on actionable information that will help improve the generation
- Consider what has already been completed vs. what's still needed
- Ask follow-up questions based on previous user responses
- Keep questions clear and easy to answer
- Group related questions together logically

Format your response as a clear, friendly message with well-organized questions.`,

  // Question generation human template
  QUESTION_GENERATION_HUMAN: `Based on the conversation history and current progress shown above, I need to ask the user for more information about: {task_description}

Please generate helpful, specific questions that will gather the information needed to proceed effectively. Consider:
- What has already been generated and what's still missing
- The user's previous responses and preferences
- Any gaps in the current work that need clarification

Create engaging questions that will help the user provide the most useful information.`,

  // Progress-based question templates
  CHARACTER_QUESTIONS: `**About Your Character:**
• What personality traits should your character have?
• What's their background story or history?
• How should they behave in conversations?
• Are there any specific quirks or mannerisms you want?
• What role do they play in their world/setting?`,

  WORLDBOOK_QUESTIONS: `**About the World/Setting:**
• What type of world or setting is this? (modern, fantasy, sci-fi, etc.)
• What locations should be included in the worldbook?
• Are there important organizations, cultures, or factions?
• What historical events or legends should be mentioned?
• How detailed should the world information be?`,

  REFINEMENT_QUESTIONS: `**Refinement & Preferences:**
• Are you satisfied with what's been generated so far?
• Should anything be changed or improved?
• What style or tone do you prefer?
• Is there anything missing that you'd like added?
• How can I make this better match your vision?`,

  // Fallback templates for when LLM fails
  FALLBACK_GENERAL: `I need some additional information to help you better. Could you please provide more details about:

• What specific aspects you'd like me to focus on
• Any particular style or tone preferences
• Whether there's anything about the current progress you'd like me to adjust
• Any additional requirements or preferences you have

Please share any details that would help me create exactly what you're looking for!`,

  // Evaluation prompts for ask-user thinking
  ASK_USER_EVALUATION_SYSTEM: `You are evaluating the quality of questions generated by the ASK_USER tool.
The tool should generate clear, relevant questions that help gather missing information for character/worldbook creation.

Evaluation criteria:
- Are the questions clear and specific?
- Do they target missing information needed for the task?
- Are they appropriate for the current context?
- Do they avoid redundancy with existing information?

Respond in JSON format:
{{
  "is_satisfied": boolean,
  "quality_score": number (0-100),
  "reasoning": "detailed explanation",
  "improvement_needed": ["specific areas to improve"],
  "next_action": "continue" | "improve" | "complete"
}}`,

  // Ask-user improvement prompts
  ASK_USER_IMPROVEMENT_SYSTEM: `You are providing improvement instructions for the ASK_USER tool.
The tool needs to generate better questions based on the evaluation feedback.

Focus on:
- Making questions more specific and actionable
- Ensuring relevance to the current task
- Avoiding redundancy
- Improving clarity and structure

Respond in JSON format:
{{
  "focus_areas": ["areas to focus on"],
  "specific_requests": ["specific improvement requests"],
  "quality_target": number (target score),
  "max_attempts": number
}}`,
}; 