import { ChatPromptTemplate } from "@langchain/core/prompts";
import { BaseToolContext } from "../../models/agent-model";
import { BaseThinking, EvaluationResult, ImprovementInstruction } from "../base-think";
import { StringOutputParser } from "@langchain/core/output_parsers";
import { ChatOpenAI } from "@langchain/openai";
import { ChatOllama } from "@langchain/ollama";

/**
 * ASK_USER Tool Thinking Module
 * 询问用户工具的思考模块
 */
export class AskUserThinking extends BaseThinking {
  constructor() {
    super("ASK_USER");
  }

  /**
   * Build evaluation prompt for ASK_USER results
   * 为ASK_USER结果构建评估提示
   */
  protected buildEvaluationPrompt(
    result: any,
    context: BaseToolContext,
    attempt: number
  ): ChatPromptTemplate {
    return ChatPromptTemplate.fromMessages([
      ["system", `You are evaluating the quality of questions generated by the ASK_USER tool.
The tool should generate clear, relevant questions that help gather missing information for character/worldbook creation.

Evaluation criteria:
- Are the questions clear and specific?
- Do they target missing information needed for the task?
- Are they appropriate for the current context?
- Do they avoid redundancy with existing information?

Respond in JSON format:
{
  "is_satisfied": boolean,
  "quality_score": number (0-100),
  "reasoning": "detailed explanation",
  "improvement_needed": ["specific areas to improve"],
  "next_action": "continue" | "improve" | "complete"
}`],
      ["human", `Current attempt: ${attempt}

Generated questions:
${JSON.stringify(result, null, 2)}

Context: The user is working on character/worldbook generation.
Current progress: ${context.task_progress.character_data ? 'Character exists' : 'No character'}, ${context.task_progress.worldbook_data?.length || 0} worldbook entries.

Evaluate the quality of these questions:`]
    ]);
  }

  /**
   * Build improvement prompt for ASK_USER
   * 为ASK_USER构建改进提示
   */
  protected buildImprovementPrompt(
    originalResult: any,
    evaluation: EvaluationResult,
    context: BaseToolContext
  ): ChatPromptTemplate {
    return ChatPromptTemplate.fromMessages([
      ["system", `You are providing improvement instructions for the ASK_USER tool.
The tool needs to generate better questions based on the evaluation feedback.

Focus on:
- Making questions more specific and actionable
- Ensuring relevance to the current task
- Avoiding redundancy
- Improving clarity and structure

Respond in JSON format:
{
  "focus_areas": ["areas to focus on"],
  "specific_requests": ["specific improvement requests"],
  "quality_target": number (target score),
  "max_attempts": number
}`],
      ["human", `Original questions:
${JSON.stringify(originalResult, null, 2)}

Evaluation feedback:
- Quality score: ${evaluation.quality_score}/100
- Reasoning: ${evaluation.reasoning}
- Issues found: ${evaluation.improvement_needed.join(', ')}

Provide specific improvement instructions:`]
    ]);
  }

  /**
   * Execute thinking chain with LLM
   * 使用LLM执行思考链
   */
  protected async executeThinkingChain(
    prompt: ChatPromptTemplate,
    context: BaseToolContext
  ): Promise<string> {
    try {
      const llm = this.createLLM(context.llm_config);
      const chain = prompt.pipe(llm).pipe(new StringOutputParser());
      return await chain.invoke({});
    } catch (error) {
      console.warn(`[ASK_USER] Thinking chain failed:`, error);
      return "Unable to process thinking at this time.";
    }
  }

  /**
   * Public methods to expose protected functionality
   */
  async evaluateResult(result: any, context: BaseToolContext, attempt: number = 1) {
    return await this.evaluate(result, context, attempt);
  }

  async generateImprovementInstruction(result: any, evaluation: any, context: BaseToolContext) {
    return await this.generateImprovement(result, evaluation, context);
  }

  async executeThinking(prompt: any, context: BaseToolContext) {
    return await this.executeThinkingChain(prompt, context);
  }

  /**
   * Create LLM instance from config
   */
  private createLLM(config: BaseToolContext["llm_config"]) {
    if (config.llm_type === "openai") {
      return new ChatOpenAI({
        modelName: config.model_name,
        openAIApiKey: config.api_key,
        configuration: {
          baseURL: config.base_url,
        },
        temperature: config.temperature,
        maxTokens: config.max_tokens,
        streaming: false,
      });
    } else if (config.llm_type === "ollama") {
      return new ChatOllama({
        model: config.model_name,
        baseUrl: config.base_url || "http://localhost:11434",
        temperature: config.temperature,
        streaming: false,
      });
    }

    throw new Error(`Unsupported LLM type: ${config.llm_type}`);
  }
} 